# Generated by Django 2.0.2 on 2018-09-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='owner_eth_address',
        ),
    ]
