# Generated by Django 2.0.2 on 2018-09-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_auto_20180909_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connection',
            name='email_sent_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
