image: python:3.6

services:
  - postgres:latest
  - trufflesuite/ganache-cli:latest
  - redis:latest

variables:
  POSTGRES_DB: ci
  ETHEREUM_NODE: http://ganache:8545
  DJANGO_SETTINGS_MODULE: bdn.settings
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/ci"

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V
  - apt-get update -q && apt-get install -y libgmp-dev gettext
  - pip install -r requirements.txt
  - cp bdn/ci_settings.py bdn/local_settings.py

styling:
  stage: build
  script:
  - flake8

coverage:
  stage: build
  script:
  - coverage run --source='.' manage.py test
  - coverage report --skip-covered
  - COVERAGE="`coverage report | python -c "import sys; print(sys.stdin.read().split()[-1])"`" python scripts/update_wiki_coverage.py
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
