image: python:3.6

services:
  - postgres:latest
  - trufflesuite/ganache-cli:latest
  - redis:latest
  - docker:dind

stages:
  - lint
  - test
  - build_production
  - release_production

variables:
  POSTGRES_DB: ci
  ETHEREUM_NODE: http://ganache:8545
  DJANGO_SETTINGS_MODULE: bdn.settings
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/ci"

cache:
  paths:
  - ~/.cache/pip/
  - ~/apps/

variables:
  CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}_${CI_BUILD_REF}
  CONTAINER_IMAGE_LATEST: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  DOCKER_DRIVER: overlay2

before_script:
  - python -V
  - apt-get update -q && apt-get install -y libgmp-dev gettext
  - pip install -r requirements.txt
  - cp bdn/ci_settings.py bdn/local_settings.py

styling:
  stage: lint
  script:
  - flake8

coverage:
  stage: test
  script:
  - coverage run --source='.' manage.py test
  - coverage report --skip-covered
  - COVERAGE="`coverage report | python -c "import sys; print(sys.stdin.read().split()[-1])"`" python scripts/update_wiki_coverage.py
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

build_production:
  stage: build_production
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.codeideo.com:edu-ico/bdn-proprietary.git
  only:
    - master

release_production:
  before_script: []
  stage: release_production
  image: docker:stable
  script:
    - docker info
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CONTAINER_IMAGE_LATEST} . -f docks/production/web/Dockerfile
    - docker push ${CONTAINER_IMAGE_LATEST}
  only:
    - master
