# Generated by Django 2.0.2 on 2018-10-26 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('subscribed', models.BooleanField(default=True)),
                ('news_subscribed', models.BooleanField(default=True)),
                ('save_wallet', models.BooleanField(default=True)),
                ('wallet', models.TextField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
