# Generated by Django 2.0.2 on 2018-10-30 09:55

from django.db import migrations


def create_user_settings(apps, schema_editor):
    User = apps.get_model('bdn_auth', 'User')
    UserSettings = apps.get_model('user_settings', 'UserSettings')
    users = User.objects.filter(usersettings__isnull=True)
    for user in users:
        user_settings = UserSettings.objects.create(user=user)
        user_settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user_settings)
    ]
