# Generated by Django 2.0.2 on 2018-08-24 13:32

from django.db import migrations


def match_eth_address_to_user(apps, schema_editor):
    Provider = apps.get_model('provider', 'Provider')
    User = apps.get_model('bdn_auth', 'User')
    for provider in Provider.objects.all():
        if not provider.eth_address:
            continue
        eth_address = provider.eth_address.strip()
        user = User.objects\
            .filter(username__iexact=eth_address)\
            .first()
        if user:
            provider.user = user
            provider.save()


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_provider_user'),
    ]

    operations = [
        migrations.RunPython(match_eth_address_to_user),
    ]
