# Generated by Django 2.0.2 on 2018-11-06 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unsubscribe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('subscribed', models.BooleanField(default=True)),
            ],
        ),
    ]
