# Generated by Django 2.0.2 on 2018-08-07 10:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
        ('category', '0001_initial'),
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=130)),
                ('description', models.TextField()),
                ('external_link', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('tutor', models.CharField(blank=True, max_length=270, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='category.Category')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.Provider')),
                ('skills', models.ManyToManyField(to='skill.Skill')),
            ],
        ),
    ]
