# Generated by Django 2.0.2 on 2018-06-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
    ]
