# Generated by Django 2.0.2 on 2018-09-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='program_title',
            field=models.CharField(blank=True, default=None, max_length=130, null=True),
        ),
    ]
