# Generated by Django 2.0.2 on 2018-10-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180930_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='external_link',
            field=models.URLField(default='https://os.university'),
        ),
    ]
