# Generated by Django 2.0.2 on 2018-06-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(to='course.Skill'),
        ),
    ]
