# Generated by Django 2.0.2 on 2018-07-23 09:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20180707_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='None', max_length=70)),
                ('eth_address', models.CharField(blank=True, max_length=42, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Department'),
        ),
        migrations.AddField(
            model_name='provider',
            name='departments',
            field=models.ManyToManyField(blank=True, null=True, to='course.Department'),
        ),
    ]
