# Generated by Django 2.0.2 on 2018-07-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20180723_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='departments',
            field=models.ManyToManyField(to='course.Department'),
        ),
    ]
