# Generated by Django 2.0.2 on 2018-07-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20180723_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='departments',
        ),
        migrations.AddField(
            model_name='provider',
            name='eth_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
