# Generated by Django 2.0.2 on 2018-07-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20180725_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
