# Generated by Django 2.0.2 on 2018-08-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_provider_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='standardized',
            field=models.BooleanField(default=False),
        ),
    ]
