# Generated by Django 2.0.2 on 2018-08-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20180820_0901'),
        ('job', '0002_auto_20180820_1444'),
    ]

    operations = [
    ]
