# Generated by Django 2.0.2 on 2018-10-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_job_external_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
