# Generated by Django 2.0.2 on 2018-10-08 12:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20181008_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=130, null=True), default=[], size=None),
        ),
    ]
