# Generated by Django 2.0.2 on 2018-10-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdn_auth', '0002_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signup',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
