# Generated by Django 2.0.2 on 2018-10-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0006_auto_20180924_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='last_name',
        ),
    ]
