# Generated by Django 2.0.2 on 2018-09-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='holder',
        ),
    ]
