# Generated by Django 2.0.2 on 2018-08-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=70)),
                ('block_hash', models.CharField(max_length=70)),
                ('block_number', models.IntegerField(default=0)),
                ('granted_to', models.CharField(max_length=42)),
                ('ipfs_hash', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
