# Generated by Django 2.0.2 on 2018-08-20 14:44

import bdn.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_auto_20180820_0904'),
    ]

    operations = [
    ]
