# Generated by Django 2.0.2 on 2018-08-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='date_last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='block_hash',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='meta_ipfs_hash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
