# Generated by Django 2.0.2 on 2018-08-20 14:58

import bdn.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_auto_20180820_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='granted_to_type',
            field=models.PositiveSmallIntegerField(choices=[(bdn.profiles.models.ProfileType(1), 1), (bdn.profiles.models.ProfileType(2), 2), (bdn.profiles.models.ProfileType(3), 3)], default=bdn.profiles.models.ProfileType(1)),
        ),
    ]
