# Generated by Django 2.0.2 on 2018-08-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_verification_granted_to_type'),
        ('verification', '0002_auto_20180820_0904'),
    ]

    operations = [
    ]
