# Generated by Django 2.0.2 on 2018-08-29 08:29

import bdn.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_verification_granted_to_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='granted_to_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'LEARNER'), (2, 'ACADEMY'), (3, 'BUSINESS')], default=bdn.profiles.models.ProfileType(1)),
        ),
    ]
