# Generated by Django 2.0.2 on 2018-08-07 15:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industry', '0001_initial'),
        ('provider', '0001_initial'),
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_eth_address', models.CharField(default='None', max_length=42)),
                ('academy_title', models.CharField(max_length=70)),
                ('academy_address', models.CharField(blank=True, max_length=42, null=True)),
                ('academy_link', models.URLField()),
                ('program_title', models.CharField(blank=True, max_length=70, null=True)),
                ('course_title', models.CharField(max_length=70)),
                ('course_link', models.URLField(blank=True, null=True)),
                ('learner_eth_address', models.CharField(max_length=42)),
                ('verified', models.BooleanField(default=False)),
                ('verification_tx', models.CharField(blank=True, max_length=100, null=True)),
                ('ipfs_hash', models.CharField(default='None', max_length=100)),
                ('score', models.FloatField(default=0.0)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('industries', models.ManyToManyField(to='industry.Industry')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.Provider')),
                ('skills', models.ManyToManyField(to='skill.Skill')),
            ],
        ),
    ]
