# Generated by Django 2.0.2 on 2018-02-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(unique=True)),
                ('academy', models.CharField(max_length=42)),
                ('course', models.CharField(max_length=42)),
                ('learner', models.CharField(max_length=42)),
                ('name', models.CharField(max_length=70)),
                ('subject', models.CharField(max_length=70)),
                ('verified', models.BooleanField(default=False)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('creator', models.CharField(max_length=42)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
    ]
