# Generated by Django 2.0.2 on 2018-07-20 11:05

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_eth_address', models.CharField(default='None', max_length=42)),
                ('academy_title', models.CharField(max_length=70)),
                ('academy_address', models.CharField(blank=True, max_length=42, null=True)),
                ('academy_link', models.URLField()),
                ('program_title', models.CharField(blank=True, max_length=70, null=True)),
                ('course_title', models.CharField(max_length=70)),
                ('course_link', models.URLField(blank=True, null=True)),
                ('subject', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), default=[], size=None)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), default=[], size=None)),
                ('learner_eth_address', models.CharField(max_length=42)),
                ('verified', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
