# Generated by Django 2.0.2 on 2018-08-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
