# Generated by Django 2.0.2 on 2018-07-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='ipfs_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
