# Generated by Django 2.0.2 on 2018-08-16 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='academy_address',
        ),
    ]
