# Generated by Django 2.0.2 on 2018-07-31 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_provider_verified'),
        ('certificate', '0002_certificate_ipfs_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Provider'),
        ),
    ]
