# Generated by Django 2.0.2 on 2018-07-19 16:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_certificate_user_eth_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), default=[], size=None),
        ),
    ]
