# Generated by Django 2.0.2 on 2018-08-24 14:42

from django.db import migrations


def match_user_eth_address_to_holder(apps, schema_editor):
    Certificate = apps.get_model('certificate', 'Certificate')
    User = apps.get_model('bdn_auth', 'User')
    for certificate in Certificate.objects.all():
        if not certificate.user_eth_address:
            continue
        eth_address = certificate.user_eth_address.strip()
        user = User.objects\
            .filter(username__iexact=eth_address)\
            .first()
        if user:
            certificate.holder = user
            certificate.save()


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_certificate_holder'),
    ]

    operations = [
        migrations.RunPython(match_user_eth_address_to_holder),
    ]
