# Generated by Django 2.0.2 on 2018-08-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_certificate_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='verification_tx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='ipfs_hash',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
