# Generated by Django 2.0.2 on 2018-08-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_auto_20180803_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='skills',
        ),
    ]
