# Generated by Django 2.0.2 on 2018-09-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_remove_certificate_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='learner_eth_address',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='verification_tx',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='verified',
        ),
    ]
