# Generated by Django 2.0.2 on 2018-08-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_provider_verified'),
        ('certificate', '0005_remove_certificate_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='skills',
            field=models.ManyToManyField(to='course.Skill'),
        ),
    ]
