# Generated by Django 2.0.2 on 2018-09-12 14:23

import bdn.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0006_auto_20180912_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='course_title',
            new_name='certificate_title',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='academy_link',
            new_name='institution_link',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='academy_title',
            new_name='institution_title',
        ),
        migrations.AddField(
            model_name='certificate',
            name='granted_to_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'LEARNER'), (2, 'ACADEMY'), (3, 'BUSINESS')], default=bdn.profiles.models.ProfileType(1)),
        ),
    ]
