# Generated by Django 2.0.2 on 2018-08-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0006_certificate_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='subject',
        ),
    ]
