# Generated by Django 2.0.2 on 2018-09-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0007_auto_20180912_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='checksum_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
