# Generated by Django 2.0.2 on 2018-08-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_provider_verified'),
        ('certificate', '0007_remove_certificate_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='categories',
            field=models.ManyToManyField(to='course.Category'),
        ),
    ]
