# Generated by Django 2.0.2 on 2018-10-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0008_certificate_checksum_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_title',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='institution_title',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='program_title',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
