# Generated by Django 2.0.2 on 2018-07-16 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=70)),
                ('last_name', models.CharField(blank=True, max_length=70)),
                ('learner_email', models.EmailField(blank=True, max_length=70)),
                ('learner_position', models.CharField(blank=True, max_length=70)),
                ('learner_specialisation', models.CharField(blank=True, max_length=70)),
                ('learner_about', models.TextField(blank=True, max_length=500)),
                ('learner_site', models.CharField(blank=True, max_length=70)),
                ('phone_number', models.CharField(blank=True, max_length=70)),
                ('learner_country', models.CharField(blank=True, max_length=70)),
                ('lerner_avatar', models.CharField(blank=True, max_length=70)),
                ('academy_name', models.CharField(blank=True, max_length=70)),
                ('academy_website', models.CharField(blank=True, max_length=70)),
                ('academy_email', models.EmailField(blank=True, max_length=70)),
                ('academy_country', models.CharField(blank=True, max_length=70)),
                ('academy_about', models.TextField(blank=True, max_length=500)),
                ('academy_logo', models.CharField(blank=True, max_length=70)),
                ('company_name', models.CharField(blank=True, max_length=70)),
                ('company_website', models.CharField(blank=True, max_length=70)),
                ('company_email', models.EmailField(blank=True, max_length=70)),
                ('company_country', models.CharField(blank=True, max_length=70)),
                ('company_about', models.TextField(blank=True, max_length=500)),
                ('company_logo', models.CharField(blank=True, max_length=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
