# Generated by Django 2.0.2 on 2018-08-15 13:58

import bdn.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_profile_type',
            field=models.PositiveSmallIntegerField(choices=[(bdn.profiles.models.ProfileType(1), 1), (bdn.profiles.models.ProfileType(2), 2), (bdn.profiles.models.ProfileType(3), 3)], default=bdn.profiles.models.ProfileType(1)),
        ),
    ]
