# Generated by Django 2.0.2 on 2018-08-20 09:04

import bdn.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active_profile_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'LEARNER'), (2, 'ACADEMY'), (3, 'BUSINESS')], default=bdn.profiles.models.ProfileType(1)),
        ),
    ]
