# Generated by Django 2.0.2 on 2018-07-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180717_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='academy_logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lerner_avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
