# Generated by Django 2.0.2 on 2018-07-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180717_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='academy_logo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lerner_avatar',
        ),
    ]
