# Generated by Django 2.0.2 on 2018-10-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20181008_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='academy_about',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_about',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='learner_about',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
