# Generated by Django 2.0.2 on 2018-10-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20181008_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='academy_about',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='academy_email',
            field=models.EmailField(blank=True, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='academy_name',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_about',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_email',
            field=models.EmailField(blank=True, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='learner_about',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='learner_email',
            field=models.EmailField(blank=True, max_length=130, null=True),
        ),
    ]
