# Generated by Django 2.0.2 on 2018-08-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_public_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='academy_logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='learner_avatar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
