# Generated by Django 2.0.2 on 2018-10-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20181008_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='learner_position',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='learner_specialisation',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
