# Generated by Django 2.0.2 on 2018-09-24 12:45

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='state',
            field=django_fsm.FSMField(default='requested', max_length=50),
        ),
    ]
