# Generated by Django 2.0.2 on 2018-08-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='dialog',
            new_name='thread',
        ),
    ]
