# Generated by Django 2.0.2 on 2018-08-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20180824_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='eth_address',
        ),
    ]
